#! /bin/sh
### BEGIN INIT INFO
# Provides: pi_fan
# Required-Start: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start: S 2 3 4 5
# Default-Stop: 
# Short-Description: contrôle de ventilateur par GPIO 
# Description: Script python pour contrôle de ventilateur en fonction de la température
### END INIT INFO

sudo python3 /home/n0ne/.scripts/fan.py &
