#! /bin/sh
### BEGIN INIT INFO
# Provides: pi_shutdown
# Required-Start: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start: S 2 3 4 5
# Default-Stop: 
# Short-Description: Arrêt de Raspberry PI par bouton GPIO 
# Description: Script python pour suveiller l'état d'un pin GPIO et execution de l'arrêt de Raspberry PI
### END INIT INFO

sudo python3 /home/n0ne/.scripts/shutdown.py &
